export const GET_CURRENCY_BAR_CHART = "GET_CURRENCY_BAR_CHART";
export const GET_CURRENCY_BAR_CHART_SUCCESS = "GET_CURRENCY_BAR_CHART_SUCCESS";

export const GET_ADVANCE_BAR_CHART = "GET_ADVANCE_BAR_CHART";
export const GET_ADVANCE_BAR_CHART_SUCCESS = "GET_ADVANCE_BAR_CHART_SUCCESS";

export const GET_USERS_CHART = "GET_USERS_CHART";
export const GET_USERS_CHART_SUCCESS = "GET_USERS_CHART_SUCCESS";

export const API_ERROR = "CURRENCY_BAR_API_ERROR";
