export const GET_CURRENCY_EXCHANGES = "GET_CURRENCY_EXCHANGES";
export const GET_CURRENCY_EXCHANGES_SUCCESS = "GET_CURRENCY_EXCHANGES_SUCCESS";

export const GET_EXCHANGE_DETAILS = "GET_EXCHANGE_DETAILS";
export const GET_EXCHANGE_DETAILS_SUCCESS = "GET_EXCHANGE_DETAILS_SUCCESS";

export const CREATE_INVOICE = "CREATE_INVOICE";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";

export const APPROVE_EXCHANGE = "APPROVE_EXCHANGE";
export const APPROVE_EXCHANGE_SUCCESS = "APPROVE_EXCHANGE_SUCCESS";
export const APPROVE_EXCHANGE_CANCELED = "APPROVE_EXCHANGE_CANCELED";

export const DECLINE_EXCHANGE = "DECLINE_EXCHANGE";
export const DECLINE_EXCHANGE_SUCCESS = "DECLINE_EXCHANGE_SUCCESS";
export const DECLINE_EXCHANGE_CANCELED = "DECLINE_EXCHANGE_CANCELED";

export const EDIT_EXCHANGE = "EDIT_EXCHANGE";
export const EDIT_EXCHANGE_SUCCESS = "EDIT_EXCHANGE_SUCCESS";

export const CLEAR_ALERT = "CLEAR_EXCHANGE_ALERT";
export const API_ERROR = "CURRENCY_EXCHANGE_ERROR";
