export const GET_LIMITS = "GET_LIMITS";
export const GET_LIMITS_SUCCESS = "GET_LIMITS_SUCCESS";

export const EDIT_LIMITS = "EDIT_LIMITS";
export const EDIT_LIMITS_SUCCESS = "EDIT_LIMITS_SUCCESS";

export const CLEAR_SUCCESS_ALERT = "CLEAR_SUCCESS_LIMITS_ALERT";
export const CLEAR_ERROR_ALERT = "CLEAR_ERROR_LIMITS_ALERT";

export const API_ERROR = "LIMITS_API_ERROR";
