export const GET_ADVANCE_DETAILS = "GET_ADVANCE_DETAILS";
export const GET_ADVANCE_DETAILS_SUCCESS = "GET_ADVANCE_DETAILS_SUCCESS";

export const APPROVE_CASH_ADVANCE = "APPROVE_CASH_ADVANCE";
export const APPROVE_CASH_ADVANCE_SUCCESS = "APPROVE_CASH_ADVANCE_SUCCESS";
export const APPROVE_CASH_ADVANCE_CANCELED = "APPROVE_CASH_ADVANCE_CANCELED";

export const DECLINE_CASH_ADVANCE = "DECLINE_CASH_ADVANCE";
export const DECLINE_CASH_ADVANCE_SUCCESS = "DECLINE_CASH_ADVANCE_SUCCESS";
export const DECLINE_CASH_ADVANCE_CANCELED = "DECLINE_CASH_ADVANCE_CANCELED";

export const CLEAR_ALERT = "ADVANCE_CLEAR_ALERT";
export const API_ERROR = "ADVANCE_API_ERROR";
