export const GET_SCHEDULE = "GET_SCHEDULE";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";

export const EDIT_SCHEDULE = "EDIT_SCHEDULE";
export const EDIT_SCHEDULE_SUCCESS = "EDIT_SCHEDULE_SUCCESS";

export const CLEAR_ALERT = "CLEAR_SCHEDULE_ALERT";
export const API_ERROR = "SCHEDULE_API_ERROR";
