export const GET_COUNTERS = "GET_COUNTERS";
export const GET_COUNTERS_SUCCESS = "GET_COUNTERS_SUCCESS";

export const CLEAR_ALERT = "COUNTERS_CLEAR_ALERT";
export const API_ERROR = "COUNTERS_API_ERROR";
