export const GET_BANKS = "GET_BANKS";
export const GET_BANKS_SUCCESS = "GET_BANKS_SUCCESS";

export const ADD_BANK = "ADD_BANK";
export const ADD_BANK_SUCCESS = "ADD_BANK_SUCCESS";

export const EDIT_BANK = "EDIT_BANK";
export const EDIT_BANK_SUCCESS = "EDIT_BANK_SUCCESS";

export const DELETE_BANK = "DELETE_BANK";
export const DELETE_BANK_SUCCESS = "DELETE_BANK_SUCCESS";

export const CLEAR_SUCCESS_ALERT = "CLEAR_BANK_SUCCESS_ALERT";
export const CLEAR_ERROR_ALERT = "CLEAR_BANK_ERROR_ALERT";
export const API_ERROR = "BANKS_API_ERROR";
