export const GET_CLIENT_DETAILS = "GET_CLIENT_DETAILS";
export const GET_CLIENT_DETAILS_SUCCESS = "GET_CLIENT_DETAILS_SUCCESS";

export const GET_CLIENT_ACTIVITY = "GET_CLIENT_ACTIVITY";
export const GET_CLIENT_ACTIVITY_SUCCESS = "GET_CLIENT_ACTIVITY_SUCCESS";

export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";

export const CLEAR_ALERT = "CLIENTS_CLEAR_ALERT";
export const API_ERROR = "CLIENTS_API_ERROR";
