export const GET_CB_ACCOUNTS = "GET_CB_ACCOUNTS";
export const GET_CB_ACCOUNTS_SUCCESS = "GET_CB_ACCOUNTS_SUCCESS";

export const ADD_CB_ACCOUNTS = "ADD_CB_ACCOUNTS";
export const ADD_CB_ACCOUNTS_SUCCESS = "ADD_CB_ACCOUNTS_SUCCESS";

export const EDIT_CB_ACCOUNTS = "EDIT_CB_ACCOUNTS";
export const EDIT_CB_ACCOUNTS_SUCCESS = "EDIT_CB_ACCOUNTS_SUCCESS";

export const CLEAR_CB_ACCOUNTS_ALERT = "CLEAR_CB_ACCOUNTS_ALERT";

export const API_ERROR = "CB_ACCOUNTS_ERROR";
