export const ADD_CURRENCY_PRICE_INIT = "ADD_CURRENCY_PRICE_INIT";
export const ADD_CURRENCY_PRICE_SUCCESS = "ADD_CURRENCY_PRICE_SUCCESS";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const API_ERROR = "CURRENCY_PRICES_API_ERROR";
