export const GET_CLIENT_BINNACLE = "GET_CLIENT_BINNACLE";
export const GET_CLIENT_BINNACLE_SUCCESS = "GET_CLIENT_BINNACLE_SUCCESS";

export const GET_ADMIN_BINNACLE = "GET_ADMIN_BINNACLE";
export const GET_ADMIN_BINNACLE_SUCCESS = "GET_ADMIN_BINNACLE_SUCCESS";

export const CLEAR_ALERT = "BINNACLE_CLEAR_ALERT";
export const API_ERROR = "BINNACLE_API_ERROR";
